# nombre de la app
spring.application.name=TaskScheduler

# ======================
# H2
# ======================
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ======================
# JPA / Hibernate
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# Thymeleaf / debug
# ======================
spring.thymeleaf.cache=false
server.error.include-message=always
server.error.include-stacktrace=always

# ======================
# tiempo límite del Solver (en segundos)
# ======================
solver.timeLimitSeconds=2


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

# ======================
# Cloudinary
# ======================
cloudinary.cloud-name=dz72vo8eo
cloudinary.api-key=419189526451643
cloudinary.api-secret=TJHePcnsRoJsjEoynOs5I3ocRKs

spring.web.resources.add-mappings=true