# nombre de la app
spring.application.name=TaskScheduler

# ======================
# MYSQL
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/task_scheduler?useSSL=false&serverTimezone=UTC
spring.datasource.username=task_user
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================
# JPA / Hibernate
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# Thymeleaf / debug
# ======================
spring.thymeleaf.cache=false
server.error.include-message=always
server.error.include-stacktrace=always

# ======================
# tiempo límite del Solver (en segundos)
# ======================
solver.timeLimitSeconds=2


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

# ======================
# Cloudinary
# ======================
cloudinary.cloud-name=dz72vo8eo
cloudinary.api-key=419189526451643
cloudinary.api-secret=${CLOUDINARY_SECRET}

spring.web.resources.add-mappings=true

# ======================
# Configuración de correo electrónico
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=escalasoes@arautos.org.br
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=false
spring.mail.properties.mail.debug=true